import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const temp=mkdtempSync(join(tmpdir(),'setwise-coach-'));
let sql=new DatabaseSync(join(temp,'workout.sqlite'));sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const adapter={prepare(text){return{bind(...values){const execute=()=>{const stmt=sql.prepare(text);if(/^\s*SELECT/i.test(text))return{results:stmt.all(...values)};const info=stmt.run(...values);return{results:[],meta:{changes:Number(info.changes)}};};return{first:async()=>execute().results[0]??null,all:async()=>execute(),run:async()=>execute(),execute};}};},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s.execute());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const coachKey='coach-test-'.padEnd(48,'c'),loginKey='login-test-'.padEnd(48,'l');
const hash=x=>createHash('sha256').update(x).digest('hex');
globalThis.__coachEnv={DB:adapter,AUTH_MODE:'standalone',OWNER_ID:'test-owner',COACH_KEY_HASH:hash(coachKey),LOGIN_KEY_HASH:hash(loginKey),SESSION_SECRET:'test-session-secret-'.padEnd(48,'s'),ASSETS:{fetch:async()=>new Response('Setwise UI')}};
await build({entryPoints:['standalone/worker.ts'],bundle:true,platform:'node',format:'esm',outfile:join(temp,'worker.mjs'),plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__coachEnv',loader:'js'}));}}]});
const worker=(await import(pathToFileURL(join(temp,'worker.mjs')))).default;
const call=(path,{method='GET',body,headers={}}={})=>worker.fetch(new Request('https://setwise.test'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}));
const auth={Authorization:'Bearer '+coachKey};
let cookie;
test('auth, routine update, reopen, start, overrides, rollback, and duplicate protection',async()=>{
 assert.equal((await call('/api/coach/context')).status,401);
 assert.equal((await call('/api/workout',{headers:{'oai-authenticated-user-id':'test-owner'}})).status,401,'standalone must not trust Sites headers');
 assert.equal((await call('/api/coach/context',{headers:{Authorization:'Bearer '+loginKey}})).status,401,'browser and coach credentials are separate');
 let login=await worker.fetch(new Request('https://setwise.test/login',{method:'POST',headers:{Origin:'https://evil.test'},body:new URLSearchParams({key:loginKey})}));assert.equal(login.status,403);
 login=await worker.fetch(new Request('https://setwise.test/login',{method:'POST',headers:{Origin:'https://setwise.test'},body:new URLSearchParams({key:loginKey})}));assert.equal(login.status,303);cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly/);
 let response=await call('/api/workout',{headers:{Cookie:cookie}});assert.equal(response.status,200);let initial=await response.json();assert.equal(initial.sets.length,1);
 const context=await (await call('/api/coach/context',{headers:auth})).json();assert.equal(context.routine.revision,0);
 const routine=structuredClone(context.routine.routine);routine.workouts[0].exercises[0].minReps=12;routine.workouts[0].exercises[0].maxReps=15;routine.workouts[0].exercises[0].sets=2;routine.workouts[0].exercises[0].targetRir=3;routine.constraints=['Keep sessions under 45 minutes'];routine.workouts[0].timeLimitMinutes=45;
 const change={requestId:'first-change',expectedRevision:0,reason:'Use a higher rep range next session',routine};
 response=await call('/api/coach/routine',{method:'PUT',headers:auth,body:change});assert.equal(response.status,200);assert.equal((await response.json()).revision,1);
 assert.equal((await call('/api/coach/routine',{method:'PUT',headers:auth,body:change})).status,200,'uncertain save retry');
 assert.equal((await call('/api/coach/routine',{method:'PUT',headers:auth,body:{...change,reason:'different'}})).status,409);
 assert.equal((await call('/api/coach/routine',{method:'PUT',headers:auth,body:{...change,requestId:'stale'}})).status,409);
 const unknown=structuredClone(change);unknown.expectedRevision=1;unknown.requestId='unknown';unknown.routine.workouts[0].exercises[0].variantId='someone-else';assert.equal((await call('/api/coach/routine',{method:'PUT',headers:auth,body:unknown})).status,400);
 const invalid=structuredClone(change);invalid.routine.workouts[0].exercises[0].minReps=40;assert.equal((await call('/api/coach/routine',{method:'PUT',headers:auth,body:invalid})).status,400);
 sql.close();sql=new DatabaseSync(join(temp,'workout.sqlite'));sql.exec('PRAGMA foreign_keys=ON');
 let d=await (await call('/api/workout',{headers:{Cookie:cookie}})).json();assert.equal(d.routine.revision,1);assert.equal(d.sessions.find(s=>s.status==='active').prescriptions.length,0,'future changes preserve current session');
 const post=body=>call('/api/workout',{method:'POST',headers:{Cookie:cookie},body});
 const active=d.sessions.find(s=>s.status==='active');await post({action:'finish',sessionId:active.id});
 assert.equal((await post({action:'start',id:'new',name:'Next',plan:active.plan,workoutId:routine.workouts[0].id,expectedRoutineRevision:0})).status,409);
 response=await post({action:'start',id:'new',name:'Next',plan:active.plan,workoutId:routine.workouts[0].id,expectedRoutineRevision:1});assert.equal(response.status,200);d=await response.json();const current=d.sessions.find(s=>s.status==='active');assert.equal(current.routineRevision,1);assert.equal(current.prescriptions[0].maxReps,15);assert.match(current.notes,/45 minutes/);
 response=await post({action:'log',id:'logged',sessionId:current.id,variantId:current.plan[0],weight:95,reps:12,rir:3,side:'left',type:'working',painLocation:'',painSeverity:0,note:'Actual set'});assert.equal(response.status,200);d=await response.json();assert.equal(d.progressions[0].recommendation.max,15);assert.equal(d.progressions[0].recommendation.targetRir,3);
 let ctx=await (await call('/api/coach/context',{headers:auth})).json();const adjust={requestId:'current-change',sessionId:current.id,expectedConfiguration:ctx.activeSession.configurationVersion,reason:'Use 10–12 reps today',workout:{name:routine.workouts[0].name,exercises:structuredClone(routine.workouts[0].exercises)}};adjust.workout.exercises[0].minReps=10;adjust.workout.exercises[0].maxReps=12;
 response=await call('/api/coach/apply',{method:'POST',headers:auth,body:adjust});assert.equal(response.status,200);
 assert.equal((await call('/api/coach/apply',{method:'POST',headers:auth,body:adjust})).status,200);
 assert.equal((await call('/api/coach/apply',{method:'POST',headers:auth,body:{...adjust,requestId:'stale-current'}})).status,409);
 d=await (await call('/api/workout',{headers:{Cookie:cookie}})).json();assert.equal(d.sets.length,2);assert.equal(d.sessions.find(s=>s.status==='active').prescriptions[0].minReps,10);assert.equal(d.routine.routine.workouts[0].exercises[0].minReps,12,'today adjustment does not alter future routine');
 if(process.env.SETWISE_QA_SNAPSHOT)writeFileSync(process.env.SETWISE_QA_SNAPSHOT,JSON.stringify(d));
 const restore={requestId:'restore',expectedRevision:1,reason:'Restore original routine',routine:context.routine.routine};assert.equal((await call('/api/coach/routine',{method:'PUT',headers:auth,body:restore})).status,200);
 const revisions=await (await call('/api/coach/history?kind=revisions',{headers:auth})).json();assert.equal(revisions.items[0].revision,2);assert.equal(revisions.nextBefore,2);const older=await (await call('/api/coach/history?kind=revisions&before=2',{headers:auth})).json();assert.equal(older.items[0].revision,1);
 const exported=await (await call('/api/export',{headers:{Cookie:cookie}})).json();assert.equal(exported.data.sets.length,2);assert.equal(exported.revisions.length,3);
 await build({entryPoints:['lib/backup.ts'],bundle:true,platform:'node',format:'esm',outfile:join(temp,'backup.mjs')});
 const {backupToSQL}=await import(pathToFileURL(join(temp,'backup.mjs')));
 exported.data.sets[1].note="quote '); DROP TABLE sets; -- stays plain text";
 const imported=new DatabaseSync(':memory:');imported.exec('PRAGMA foreign_keys=ON');
 for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())imported.exec(readFileSync('drizzle/'+f,'utf8'));
 imported.exec(backupToSQL(exported,'import-owner'));
 assert.equal(imported.prepare('SELECT count(*) n FROM sets').get().n,2);
 assert.equal(imported.prepare('SELECT note FROM sets WHERE id = ?').get(exported.data.sets[1].id).note,exported.data.sets[1].note);
 assert.equal(imported.prepare('SELECT owner FROM sets LIMIT 1').get().owner,'import-owner');
 assert.equal(imported.prepare('SELECT count(*) n FROM routine_revisions').get().n,3);
 const broken=structuredClone(exported);broken.data.sets[0].variantId='missing';assert.throws(()=>backupToSQL(broken,'import-owner'),/dangling/);
 imported.close();

 assert.equal((await post({action:'finish',sessionId:current.id})).status,200);
 assert.equal((await call('/api/coach/apply',{method:'POST',headers:auth,body:{...adjust,requestId:'finished'}})).status,409);
 globalThis.__coachEnv.OWNER_ID='second-owner';ctx=await (await call('/api/coach/context',{headers:auth})).json();assert.equal(ctx.routine.revision,0);assert.equal(ctx.recentSets.length,1);
 delete globalThis.__coachEnv.AUTH_MODE;assert.equal((await call('/api/coach/context',{headers:auth})).status,503,'misconfigured external deployments fail closed');
 sql.close();rmSync(temp,{recursive:true,force:true});
});
