import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const temp=mkdtempSync(join(tmpdir(),'setwise-coach-'));
let sql=new DatabaseSync(join(temp,'workout.sqlite'));sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const adapter={prepare(text){return{bind(...values){const execute=()=>{const stmt=sql.prepare(text);if(/^\s*SELECT/i.test(text))return{results:stmt.all(...values)};const info=stmt.run(...values);return{results:[],meta:{changes:Number(info.changes)}};};return{first:async()=>execute().results[0]??null,all:async()=>execute(),run:async()=>execute(),execute};}};},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s.execute());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const coachKey='coach-test-'.padEnd(48,'c'),loginKey='login-test-'.padEnd(48,'l');
const hash=x=>createHash('sha256').update(x).digest('hex');
globalThis.__coachEnv={DB:adapter,AUTH_MODE:'standalone',OWNER_ID:'test-owner',COACH_KEY_HASH:hash(coachKey),LOGIN_KEY_HASH:hash(loginKey),SESSION_SECRET:'test-session-secret-'.padEnd(48,'s'),ASSETS:{fetch:async()=>new Response('Setwise UI')}};
await build({entryPoints:['standalone/worker.ts'],bundle:true,platform:'node',format:'esm',outfile:join(temp,'worker.mjs'),plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__coachEnv',loader:'js'}));}}]});
const worker=(await import(pathToFileURL(join(temp,'worker.mjs')))).default;
const call=(path,{method='GET',body,headers={}}={})=>worker.fetch(new Request('https://setwise.test'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}));

test('mobile auth, deterministic logging, validated coach proposals, apply/retry, stale protection and provider failure',async()=>{
 const originalFetch=globalThis.fetch;let providerCalls=0,answer;
 globalThis.fetch=async(url,options)=>{providerCalls++;assert.equal(url,'https://openrouter.ai/api/v1/chat/completions');const request=JSON.parse(options.body);assert.equal(request.response_format.type,'json_schema');assert.equal(request.provider.require_parameters,true);return Response.json({choices:[{message:{content:JSON.stringify(answer)}}]});};
 try{
  assert.equal((await call('/api/workout')).status,401);
  assert.equal((await call('/api/coach')).status,401);
  assert.equal((await call('/mcp')).status,404);
  assert.equal((await call('/api/coach/context')).status,404);
  assert.equal((await call('/api/workout',{headers:{'oai-authenticated-user-id':'test-owner'}})).status,401);
  let login=await worker.fetch(new Request('https://setwise.test/login',{method:'POST',headers:{Origin:'https://evil.test'},body:new URLSearchParams({key:loginKey})}));assert.equal(login.status,403);
  login=await worker.fetch(new Request('https://setwise.test/login',{method:'POST',headers:{Origin:'https://setwise.test'},body:new URLSearchParams({key:loginKey})}));assert.equal(login.status,303);assert.match(login.headers.get('set-cookie'),/HttpOnly/);
  const cookie=login.headers.get('set-cookie').split(';')[0],headers={Cookie:cookie,Origin:'https://setwise.test'};
  const post=body=>call('/api/workout',{method:'POST',headers,body});
  const coach=body=>call('/api/coach',{method:'POST',headers,body});
  const read=async()=> (await call('/api/workout',{headers})).json();
  const propose=message=>coach({action:'propose',requestId:crypto.randomUUID(),message});
  let data=await read();assert.equal(data.sets.length,0);assert.equal(data.sessions.length,0);await post({action:'start',id:crypto.randomUUID(),name:'Test workout',plan:data.variants.slice(0,5).map(v=>v.id)});data=await read();let session=data.sessions.find(s=>s.status==='active'),variant=data.variants.find(v=>v.id===session.plan[0]);
  assert.equal((await (await call('/api/coach',{headers})).json()).configured,false);
  assert.equal((await propose('Two sets today')).status,503);
  const logged={action:'log',id:crypto.randomUUID(),sessionId:session.id,variantId:variant.id,weight:95,reps:10,rir:2,side:'left',type:'working',painLocation:'',painSeverity:0,note:'Test set'};
  assert.equal((await post(logged)).status,200);assert.equal((await post(logged)).status,200);
  assert.equal((await post({...logged,reps:11})).status,409);
  data=await read();assert.equal(data.sets.filter(s=>s.id===logged.id).length,1);assert.equal(data.progressions.length,1);assert.equal(providerCalls,0,'ordinary logging never calls an LLM');
  const initialSets=JSON.stringify(data.sets);
  globalThis.__coachEnv.OPENROUTER_API_KEY='test-key-not-real';
  answer={reply:'Proposed two sets today.',operation:{type:'adjust_workout',workout:{name:'Short workout',exercises:session.plan.map(id=>({variantId:id,minReps:8,maxReps:12,sets:2,targetRir:3}))}}};
  const request={action:'propose',requestId:crypto.randomUUID(),message:'Two sets today'};
  let response=await coach(request);assert.equal(response.status,200);let p=(await response.json()).proposal;
  assert.equal((await coach(request)).status,200);assert.equal(providerCalls,1,'proposals are idempotent');
  data=await read();assert.equal(data.sessions.find(s=>s.id===session.id).name,session.name,'proposing does not modify workouts');
  assert.equal((await coach({action:'apply',requestId:p.id,operation:{type:'delete'}})).status,400,'client cannot change stored operations');
  response=await coach({action:'apply',requestId:p.id});assert.equal(response.status,200);
  data=(await response.json()).snapshot;assert.equal(data.sessions.find(s=>s.id===session.id).name,'Short workout');assert.equal(JSON.stringify(data.sets),initialSets);
  assert.equal((await coach({action:'apply',requestId:p.id})).status,200);assert.equal(providerCalls,1,'applying never invokes LLM');
  p=(await (await propose('Another adjustment')).json()).proposal;
  assert.equal((await post({action:'session',sessionId:session.id,name:'Manual edit',notes:'Keep my note',plan:session.plan})).status,200);
  assert.equal((await coach({action:'apply',requestId:p.id})).status,409,'stale proposals cannot overwrite manual edits');
  answer={reply:'Invalid exercise.',operation:{type:'adjust_workout',workout:{name:'Bad',exercises:[{variantId:'not-owned',minReps:8,maxReps:12,sets:2,targetRir:2}]}}};
  assert.equal((await propose('Unknown exercise')).status,502);
  answer={reply:'Delete all history',operation:{type:'delete_history'}};assert.equal((await propose('Malformed operation')).status,502);
  answer={reply:'Routine ready for review.',operation:{type:'replace_routine',routine:{name:'Three days',notes:'Simple routine',constraints:[],workouts:[{id:'day-a',name:'Day A',notes:'',timeLimitMinutes:45,exercises:session.plan.map(id=>({variantId:id,minReps:10,maxReps:12,sets:3,targetRir:2}))}]}}};
  p=(await (await propose('Build my routine')).json()).proposal;
  const staleRoutine=(await (await propose('Alternate routine')).json()).proposal;
  assert.equal((await coach({action:'apply',requestId:p.id})).status,200);
  assert.equal((await coach({action:'apply',requestId:staleRoutine.id})).status,409);
  data=await read();assert.equal(data.routine.revision,1);assert.equal(data.sessions.find(s=>s.id===session.id).name,'Manual edit','routine applies only to future workouts');
  globalThis.fetch=async()=>new Response('provider failure',{status:500});
  assert.equal((await propose('Provider unavailable')).status,502);
  assert.equal((await post({...logged,id:crypto.randomUUID(),side:'right'})).status,200,'logging works while provider fails');
  assert.equal((await call('/api/coach',{method:'POST',headers:{...headers,Origin:'https://evil.test'},body:{action:'apply',requestId:p.id}})).status,403);
  assert.equal((await call('/api/coach',{method:'POST',headers:{Authorization:'Bearer '+coachKey},body:request})).status,401,'no external coach credential access');
  assert.equal((await post({action:'finish',sessionId:session.id})).status,200);
  assert.equal((await post({action:'start',id:crypto.randomUUID(),name:'ignored',plan:session.plan,workoutId:'day-a',expectedRoutineRevision:1})).status,200);
  data=await read();assert.equal(data.sessions.find(s=>s.status==='active').name,'Day A');
  const exported=await (await call('/api/export',{headers})).json();assert.ok(exported.data.sets.length>=2);
  sql.prepare("INSERT INTO coach_requests(owner,id,created_at,message,status) VALUES (?,?,?,?,?)").run('test-owner','rate-limit',Date.now(),'test','failed');
  while(sql.prepare('SELECT count(*) n FROM coach_requests').get().n<10)sql.prepare("INSERT INTO coach_requests(owner,id,created_at,message,status) VALUES (?,?,?,?,?)").run('test-owner',crypto.randomUUID(),Date.now(),'test','failed');
  assert.equal((await propose('Rate limited')).status,429);
  // The program is stored through the authenticated API and survives new snapshots.
  data=await read();const active=data.sessions.find(s=>s.status==='active');
  const programRoutine={name:'RTF API test',notes:'',constraints:[],program:{id:'rtf-api-cycle',lifts:['a','b'].map(workoutId=>({workoutId,variantId:variant.id,profile:'main',trainingMax:100}))},workouts:['a','b'].map(id=>({id,name:id,notes:'',timeLimitMinutes:null,exercises:[{variantId:variant.id,minReps:5,maxReps:5,sets:2,targetRir:0}]}))};
  const buddy=data.variants.find(v=>v.id!==variant.id).id;
  for(const w of programRoutine.workouts){w.exercises.push({variantId:buddy,minReps:8,maxReps:12,sets:2,targetRir:0});w.supersets=[[variant.id,buddy]];}
  const save={action:'save_routine',requestId:'rtf-api-save',expectedRevision:1,reason:'test program',routine:programRoutine};
  assert.equal((await post(save)).status,200);assert.equal((await post(save)).status,200);
  assert.equal((await post({action:'finish',sessionId:active.id})).status,200);
  const begin=workoutId=>post({action:'start',id:crypto.randomUUID(),name:workoutId,plan:[variant.id],workoutId,expectedRoutineRevision:2});
  assert.equal((await begin('a')).status,200);data=await read();let programmed=data.sessions.find(s=>s.status==='active');
  assert.equal(programmed.rules.program.week,1);assert.equal(programmed.rules.program.lifts[0].weight.left,70);
  assert.deepEqual(programmed.rules.supersets,[[variant.id,buddy]],'saved pairings freeze into the active session');
  const priorProgram=JSON.stringify(programmed.rules.program),priorSets=JSON.stringify(data.sets);
  assert.equal((await post({action:'supersets',sessionId:programmed.id,supersets:[],expectedSupersets:[[variant.id,buddy]]})).status,200);
  assert.equal((await post({action:'supersets',sessionId:programmed.id,supersets:[[variant.id,buddy]],expectedSupersets:[[variant.id,buddy]]})).status,409,'stale pairing update rejected');
  assert.equal((await post({action:'supersets',sessionId:programmed.id,supersets:[[variant.id,variant.id]],expectedSupersets:[]})).status,400);
  assert.equal((await post({action:'supersets',sessionId:programmed.id,supersets:[[variant.id,'foreign']],expectedSupersets:[]})).status,400);
  assert.equal((await post({action:'supersets',sessionId:programmed.id,supersets:[[variant.id,buddy]],expectedSupersets:[]})).status,200);
  data=await read();assert.equal(JSON.stringify(data.sessions.find(s=>s.id===programmed.id).rules.program),priorProgram);assert.equal(JSON.stringify(data.sets),priorSets);
  let last;
  for(const side of ['left','right'])for(let i=0;i<2;i++){
   last={...logged,id:crypto.randomUUID(),sessionId:programmed.id,weight:70,reps:i===0?5:side==='left'?12:9,rir:null,side};
   assert.equal((await post(last)).status,200);
  }
  assert.equal((await post(last)).status,200,'lost response retry has no duplicate');
  assert.equal((await post({action:'undo',setId:last.id,sessionId:programmed.id})).status,200);
  assert.equal((await post(last)).status,200);
  assert.equal((await post({action:'finish',sessionId:programmed.id})).status,200);
  assert.equal((await post({action:'finish',sessionId:programmed.id})).status,200,'finish retry advances once');
  assert.equal((await post(last)).status,200,'saved set can be acknowledged after finish');
  assert.equal((await begin('a')).status,400,'cannot jump ahead of remaining week-one workout');
  assert.equal((await begin('b')).status,200);data=await read();programmed=data.sessions.find(s=>s.status==='active');
  assert.equal((await post({action:'finish',sessionId:programmed.id})).status,200);
  assert.equal((await begin('b')).status,200);data=await read();programmed=data.sessions.find(s=>s.status==='active');
  assert.equal(programmed.rules.program.week,1,'empty session does not advance week');
  assert.equal((await post({...logged,id:crypto.randomUUID(),sessionId:programmed.id,weight:70,reps:5,rir:null})).status,200);
  assert.equal((await post({action:'finish',sessionId:programmed.id})).status,200);
  assert.equal((await begin('a')).status,200);data=await read();programmed=data.sessions.find(s=>s.status==='active');
  assert.equal(programmed.rules.program.week,2);
  assert.equal(programmed.rules.program.lifts[0].trainingMax.left,101);
  assert.equal(programmed.rules.program.lifts[0].trainingMax.right,98);
 }finally{globalThis.fetch=originalFetch;sql.close();rmSync(temp,{recursive:true,force:true});}
});
