import test from 'node:test';
import assert from 'node:assert/strict';
import {accountHarness} from './account-harness.mjs';
test('RTF coach proposes and applies real edits, preserves logged work and skips, and keeps future periodization',async()=>{
 const h=await accountHarness(),originalFetch=globalThis.fetch;let answer,calls=0;
 try{
 globalThis.__accountEnv.OPENROUTER_API_KEY='test-only';
 globalThis.fetch=async(url,options)=>{calls++;const body=JSON.parse(options.body);assert.ok(body.messages.some(m=>m.content.includes('CAN and SHOULD return adjust_workout')));assert.ok(!body.messages.some(m=>m.content.includes('return operation:null. Do not replace')));return Response.json({choices:[{message:{content:JSON.stringify(answer)}}]});};
 const cookie=(await h.login(h.loginKey)).headers.get('set-cookie').split(';')[0],read=async()=> (await h.call('/api/workout',cookie)).json(),post=a=>h.call('/api/workout',cookie,a),coach=a=>h.call('/api/coach',cookie,a);
 let s=await read();const bench=s.variants.find(v=>v.id.endsWith('-bench')),row=s.variants.find(v=>v.id.endsWith('-row')),extension=s.variants[0];
 const exercises=[bench,row,extension].map(v=>({variantId:v.id,minReps:8,maxReps:12,sets:2,targetRir:0}));
 const routine={name:'RTF',notes:'',constraints:['Keep my constraint'],workouts:[{id:'a',name:'A',notes:'',timeLimitMinutes:null,exercises,supersets:[[row.id,extension.id]]}],program:{id:'rtf-coach',lifts:[{workoutId:'a',variantId:bench.id,profile:'main',trainingMax:100},{workoutId:'a',variantId:row.id,profile:'accessory',startingWeight:50},{workoutId:'a',variantId:extension.id,profile:'main',trainingMax:120}]}};
 await post({action:'save_routine',requestId:'routine',expectedRevision:0,reason:'test',routine});await post({action:'start',id:'today',name:'A',plan:exercises.map(e=>e.variantId),workoutId:'a',expectedRoutineRevision:1});
 s=await read();const rules=s.sessions[0].rules;rules.program.lifts.find(l=>l.variantId===extension.id).trainingMax={left:125,right:125};h.sql.prepare('UPDATE sessions SET rules=? WHERE id=?').run(JSON.stringify(rules),'today');
 const log=(id,v,weight,reps)=>post({action:'log',id,sessionId:'today',variantId:v.id,weight,reps,rir:null,side:'both',type:'working',painLocation:'',painSeverity:0,note:''});
 await log('bench-first',bench,70,5);await log('row-first',row,50,10);s=await read();const before=s,unchanged=s.sessions[0].rules.program.lifts[0];
 answer={reply:'Proposed skipping the two accessories today. Tap Apply to save.',operation:{type:'adjust_workout',workout:{name:'A',exercises:[exercises[0]]}}};
 const requestId=crypto.randomUUID();let r=await coach({action:'propose',requestId,message:'Skip row and leg extension today'});assert.equal(r.status,200);assert.ok((await r.json()).proposal.operation);assert.deepEqual((await read()).sessions,before.sessions,'proposals do not save');
 r=await coach({action:'apply',requestId});assert.equal(r.status,200);s=(await r.json()).snapshot;const active=s.sessions[0];assert.deepEqual(s.sets,before.sets);assert.deepEqual(s.routine,before.routine);assert.ok(active.rules.skipped.includes(row.id));assert.ok(active.rules.skipped.includes(extension.id));assert.ok(active.plan.includes(row.id),'logged exercise remains visible');assert.ok(!active.plan.includes(extension.id),'unlogged skipped exercise leaves lineup');assert.deepEqual(active.rules.program.lifts[0],unchanged);assert.deepEqual(active.rules.supersets,[]);
 assert.equal((await coach({action:'apply',requestId})).status,200);assert.equal(calls,1,'Apply/retry never calls the model');
 answer={reply:'Proposed one bench set today.',operation:{type:'adjust_workout',workout:{name:'A',exercises:[{...exercises[0],sets:1}]}}};const reduced=crypto.randomUUID();await coach({action:'propose',requestId:reduced,message:'Only one bench set today'});assert.equal((await coach({action:'apply',requestId:reduced})).status,200);s=await read();assert.equal(s.sessions[0].rules.program.lifts[0].sets,1);assert.equal(s.sessions[0].rules.program.lifts[0].modified,true);
 await post({action:'finish',sessionId:'today'});await post({action:'start',id:'next',name:'A',plan:exercises.map(e=>e.variantId),workoutId:'a',expectedRoutineRevision:1});s=await read();const next=s.sessions.find(s=>s.id==='next');assert.equal(next.rules.program.lifts[0].trainingMax.both,100,'modified lift holds its max');assert.equal(next.rules.program.lifts.find(l=>l.variantId===extension.id).trainingMax.left,125,'skipped unlogged lift retains earned max');
 const future=structuredClone(routine);delete future.program;delete future.workouts[0].supersets;future.name='Updated future plan';answer={reply:'Proposed a future plan edit.',operation:{type:'replace_routine',routine:future}};const futureId=crypto.randomUUID();r=await coach({action:'propose',requestId:futureId,message:'Rename my future plan'});assert.equal(r.status,200);const proposal=(await r.json()).proposal;assert.deepEqual(proposal.operation.routine.program,routine.program);assert.deepEqual(proposal.operation.routine.workouts[0].supersets,routine.workouts[0].supersets);assert.equal((await coach({action:'apply',requestId:futureId})).status,200);assert.equal((await read()).routine.routine.program.id,'rtf-coach');
 }finally{globalThis.fetch=originalFetch;h.close();}
});
