'use client';
import {useEffect,useRef,useState} from 'react';
import {Dumbbell,ArrowUpRight,Plus,Minus,Check,ChevronDown,ChevronRight,History,SlidersHorizontal,MessageCircle,ArrowRight,NotebookPen,Undo2,ShieldCheck,LoaderCircle,Activity,X,Flag,ArrowLeft,CheckCheck} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Switch} from '@/components/ui/switch';
import {Toaster,toast} from 'sonner';
import {recommend} from '@/lib/coach';
import {newId} from '@/lib/id';
import type {Snapshot,Variant,Session,Side,SetType,LoggedSet} from '@/lib/model';
const empty:Snapshot={exercises:[],variants:[],sessions:[],sets:[],messages:[],progressions:[]};
const date=(n:number)=>n?new Date(n).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Date not supplied';
const typeLabels={working:'Working',warmup:'Warmup',backoff:'Backoff',drop:'Drop set'};
const sideLabel=(s:Side)=>s==='left'?'L':s==='right'?'R':s==='unknown'?'Side unknown':'';
function Choice({value,onChange,label,items}:{value:string;onChange:(s:string)=>void;label:string;items:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent position="popper">{items.map(([id,name])=><SelectItem value={id} key={id} className="choice-item">{name}</SelectItem>)}</SelectContent></Select>;}
function Counter({label,value,onChange,step=1,unit,max=2000}:{label:string;value:number|null;onChange:(v:number)=>void;step?:number;unit?:string;max?:number}){return <div className="counter"><div className="field-label">{label}<span>{unit}</span></div><div className="counter-controls"><button aria-label={`Decrease ${label.toLowerCase()}`} onClick={()=>onChange(Math.max(0,Math.round(((value??0)-step)*100)/100))}><Minus size={23}/></button><input aria-label={label} inputMode="decimal" type="number" min="0" max={max} step={step} value={value??''} placeholder="—" onChange={e=>onChange(Math.min(max,Math.max(0,Number(e.target.value))))}/><button aria-label={`Increase ${label.toLowerCase()}`} onClick={()=>onChange(Math.min(max,Math.round(((value??0)+step)*100)/100))}><Plus size={23}/></button></div></div>;}
function Segments({value,onChange,label,items}:{value:string;onChange:(v:string)=>void;label:string;items:{id:string;label:string;hint?:string}[]}){return <RadioGroup value={value} onValueChange={onChange} aria-label={label} className="segments" style={{gridTemplateColumns:`repeat(${items.length},1fr)`}}>{items.map(i=><label className={`segment ${value===i.id?'selected':''}`} key={i.id}><RadioGroupItem value={i.id} aria-label={i.label}/><span>{i.label}</span>{i.hint&&<small>{i.hint}</small>}</label>)}</RadioGroup>;}
export default function WorkoutApp({initialData}:{initialData?:Snapshot}){
 const [data,setData]=useState<Snapshot>(initialData??empty),[loading,setLoading]=useState(!initialData),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('train');
 const [selected,setSelected]=useState(initialData?.sessions.find(s=>s.status==='active')?.plan[0]??''),[side,setSide]=useState<Side>('left'),[kind,setKind]=useState<SetType>('working'),[draft,setDraft]=useState<{weight:number|null;reps:number}|null>(null),[rir,setRir]=useState('2');
 const [panel,setPanel]=useState(''),[coachText,setCoachText]=useState(''),[painLocation,setPainLocation]=useState(''),[painSeverity,setPainSeverity]=useState(0),[setNote,setSetNote]=useState('');
 const [sessionName,setSessionName]=useState('Leg day'),[notes,setNotes]=useState(''),[historyId,setHistoryId]=useState(''),[historyVariant,setHistoryVariant]=useState('all');
 const [clock,setClock]=useState(Date.now()),[lastSaved,setLastSaved]=useState(false),[targetVariant,setTargetVariant]=useState<Variant|null>(null);
 const [form,setForm]=useState({exerciseId:'new',baseName:'',name:'',equipment:'Dumbbells',unilateral:false,loadMode:'per dumbbell',increment:5,minReps:8,maxReps:12,defaultSets:3});
 const loadedOnce=useRef(false);
 const inFlight=useRef(false),pending=useRef<{key:string;id:string}|null>(null);
 const session=data.sessions.find(s=>s.status==='active');
 const variant=data.variants.find(v=>v.id===selected)??data.variants.find(v=>v.id===session?.plan[0])??data.variants[0];
 const activeSide:Side=variant?.unilateral?side:'both';
 const rec=variant&&session?recommend(variant,session,data.sets,activeSide,kind,clock):null;
 const weight=draft?draft.weight:rec?.weight??null,reps=draft?.reps??rec?.reps??10;
 const workoutSets=data.sets.filter(s=>s.sessionId===session?.id).sort((a,b)=>a.createdAt-b.createdAt);
 const currentSets=workoutSets.filter(s=>s.variantId===variant?.id);
 const previous=data.sets.filter(s=>s.variantId===variant?.id&&s.sessionId!==session?.id&&s.type==='working'&&(s.side===activeSide||s.side==='unknown')).sort((a,b)=>b.createdAt-a.createdAt);
 const previousSession=previous[0]?.sessionId;
 const previousSets=previous.filter(s=>s.sessionId===previousSession);
 const count=currentSets.filter(s=>s.type!=='warmup'&&s.side===activeSide).length;
 const goal=session?.rules.maxSets??variant?.defaultSets??3;
 async function reload(){setLoading(true);setError('');try{const r=await fetch('/api/workout',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);if(!loadedOnce.current){const active=d.sessions.find((s:Session)=>s.status==='active');const last=d.sets.filter((s:LoggedSet)=>s.sessionId===active?.id).sort((a:LoggedSet,b:LoggedSet)=>b.createdAt-a.createdAt)[0];setSelected(last?.variantId||active?.plan[0]||d.variants[0]?.id);setSide(last?.side==='left'?'right':'left');loadedOnce.current=true;}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(!initialData)void reload();const timer=setInterval(()=>setClock(Date.now()),15000);return()=>clearInterval(timer);},[]);
 async function mutate(body:Record<string,unknown>):Promise<Snapshot|null>{
  if(inFlight.current)return null;inFlight.current=true;setBusy(true);setError('');
  try{const r=await fetch('/api/workout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setLastSaved(true);return d;}catch(e){setError((e as Error).message);return null;}finally{inFlight.current=false;setBusy(false);}
 }
 function choose(id:string){setSelected(id);setSide('left');setKind('working');setDraft(null);setRir('2');setPainLocation('');setPainSeverity(0);setSetNote('');setPanel('');setTab('train');}
 async function log(){if(!session||!variant||weight===null)return;
  const payload={action:'log',sessionId:session.id,variantId:variant.id,weight,reps,rir:Number(rir),side:activeSide,type:kind,painLocation,painSeverity,note:setNote};
  const key=JSON.stringify(payload);if(pending.current?.key!==key)pending.current={key,id:newId()};
  const d=await mutate({...payload,id:pending.current!.id});if(!d)return;pending.current=null;
  setDraft(null);setKind('working');setPainSeverity(0);setPainLocation('');setSetNote('');setRir('2');setClock(Date.now());
  if(variant.unilateral)setSide(activeSide==='left'?'right':'left');
  toast.success(`${weight} lb × ${reps} saved${variant.unilateral?` · ${activeSide} side`:''}`);
  if('vibrate' in navigator)navigator.vibrate(30);
 }
 async function tell(text=coachText){if(!session||!variant||!text.trim())return;const key=`coach:${session.id}:${text}`;if(pending.current?.key!==key)pending.current={key,id:newId()};const d=await mutate({action:'coach',id:pending.current!.id,sessionId:session.id,variantId:variant.id,message:text});if(d){pending.current=null;setCoachText('');setDraft(null);setClock(Date.now());toast.success('Workout updated');}}
 async function start(){const plan=data.sessions.filter(s=>s.status!=='seed').sort((a,b)=>b.startedAt-a.startedAt)[0]?.plan??data.variants.slice(0,5).map(v=>v.id);const d=await mutate({action:'start',id:newId(),name:sessionName.trim()||'Workout',plan});if(d){setTab('train');choose(d.sessions.find(s=>s.status==='active')!.plan[0]);}}
 function editSession(){setNotes(session?.notes??'');setSessionName(session?.name??'Workout');setPanel('session');}
 async function addToPlan(id:string){if(!session)return;const d=await mutate({action:'session',sessionId:session.id,name:session.name,notes:session.notes,plan:[...session.plan,id]});if(d)choose(id);}
 function nextExercise(){
  if(!session||!variant)return;
  const available=(v:Variant,side:Side)=>['ready','calibrate'].includes(recommend(v,session,data.sets,side,'working',clock).status);
  if(variant.unilateral){const other=activeSide==='left'?'right':'left';if(available(variant,other)){setSide(other);setKind('working');setDraft(null);return;}}
  const start=session.plan.indexOf(variant.id);const ordered=session.plan.slice(start+1).concat(session.plan.slice(0,start));
  for(const id of ordered){const v=data.variants.find(v=>v.id===id);if(!v)continue;for(const side of (v.unilateral?['left','right']:['both']) as Side[]){if(available(v,side)){choose(id);setSide(side==='right'?'right':'left');return;}}}
  setPanel('finish');
 }
 function ruleChips(s:Session){const r=s.rules;return <div className="rule-chips">{r.easy&&<span>Easy mode</span>}{r.maxSets&&<span>{r.maxSets} sets / side</span>}{r.minReps&&<span>{r.minReps}–{r.maxReps} reps</span>}{r.targetRir!==undefined&&<span>{r.targetRir}{r.targetRir===3?'+':''} RIR</span>}{r.deadline&&<span>{Math.max(0,Math.ceil((r.deadline-clock)/60000))} min left</span>}{!!r.skipped?.length&&<span>{r.skipped.length} skipped</span>}</div>;}
 function exerciseList(picker=false){return <div className="exercise-list">{(session?.plan??[]).map((id,i)=>{const v=data.variants.find(v=>v.id===id);if(!v)return null;const sets=workoutSets.filter(s=>s.variantId===id&&s.type!=='warmup');const n=v.unilateral?Math.min(sets.filter(s=>s.side==='left').length,sets.filter(s=>s.side==='right').length):sets.length;const done=n>=(session?.rules.maxSets??v.defaultSets),skipped=session?.rules.skipped?.includes(id);return <button className={`exercise-row ${variant?.id===id?'active':''}`} key={id} onClick={()=>choose(id)}><span className={`exercise-number ${done?'done':''}`}>{done?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span><strong>{v.name}</strong><small>{skipped?'Skipped today':`${n} / ${session?.rules.maxSets??v.defaultSets} sets${v.unilateral?' per side':''}`}</small></span>{variant?.id===id?<span className="now-label">NOW</span>:<ChevronRight size={17}/>}</button>;})}{picker&&data.variants.filter(v=>!session?.plan.includes(v.id)).map(v=><button key={v.id} className="exercise-row" disabled={busy} onClick={()=>addToPlan(v.id)}><Plus size={20}/><span><strong>{v.name}</strong><small>Add to this workout</small></span></button>)}</div>;}
 function setRows(sets:LoggedSet[],undo=false){return <div className="set-list">{sets.map((s,i)=><div className="set-row" key={s.id}><span className="set-index">{sideLabel(s.side)||String(i+1).padStart(2,'0')}</span><div><strong>{s.weight} <small>lb</small> × {s.reps}</strong><span className="set-meta">{typeLabels[s.type]} · {s.rir===null?'RIR unknown':`${s.rir===3?'3+':s.rir} RIR`}{s.painSeverity>0?` · ${s.painLocation} pain ${s.painSeverity}/10`:''}</span>{s.note&&<p className="set-note">{s.note}</p>}</div>{undo&&s.id===workoutSets.at(-1)?.id?<button className="icon-button" aria-label="Undo last set" disabled={busy} onClick={async()=>{const d=await mutate({action:'undo',setId:s.id,sessionId:s.sessionId});if(d){setSide(s.side==='right'?'right':'left');setDraft(null);toast('Last set undone');}}}><Undo2 size={18}/></button>:<Check size={17} className="saved-icon"/>}</div>)}</div>;}
 const historySession=data.sessions.find(s=>s.id===historyId);
 return <div className="app-shell"><Toaster position="top-center" richColors/><header className="app-header"><a className="brand" href="/" aria-label="Setwise home"><span className="brand-mark"><Dumbbell size={23}/></span>setwise<span className="brand-period">.</span></a><span className="private-label"><ShieldCheck size={15}/> Personal training log</span><span className="header-avatar">JK</span></header>
 <Tabs value={tab} onValueChange={setTab} className="app-tabs"><TabsList className="app-nav" aria-label="Main navigation"><TabsTrigger value="train"><Dumbbell/><span>Train</span></TabsTrigger><TabsTrigger value="history"><History/><span>History</span></TabsTrigger><TabsTrigger value="exercises"><SlidersHorizontal/><span>Exercises</span></TabsTrigger><TabsTrigger value="coach"><MessageCircle/><span>Coach</span></TabsTrigger></TabsList>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>void reload()} disabled={busy}>Reload</button></div>}
 {loading?<div className="loading"><LoaderCircle className="spin"/><h2>Opening your workout…</h2><p>Your history stays with your account.</p></div>:!data.variants.length?<div className="loading"><ShieldCheck/><h2>Workouts are unavailable</h2><p>Use Reload above to reconnect to your account.</p></div>:<>
 <TabsContent value="train">
 {session&&variant&&rec?<><div className="page-heading"><div><p className="eyebrow">YOUR WORKOUT</p><h1>{session.name}<button className="icon-button" aria-label="Workout notes and settings" onClick={editSession}><NotebookPen size={19}/></button></h1><p className="heading-meta">{date(session.startedAt)}<span>·</span>{workoutSets.length} {workoutSets.length===1?'set':'sets'} logged</p></div><button className="quiet-button finish-button" onClick={()=>setPanel('finish')}>Finish <Flag size={16}/></button></div>
 <div className="training-layout"><aside className="workout-sidebar"><div className="section-heading"><h2>In this workout</h2><span>{session.plan.length}</span></div>{exerciseList()}<button className="add-exercise" onClick={()=>setPanel('picker')}><Plus size={18}/> Add exercise</button><div className="session-aside"><NotebookPen size={19}/><div><h3>Workout notes</h3><p>{session.notes||'Add a focus or constraint for today.'}</p><button onClick={editSession}>{session.notes?'Edit notes':'Add a note'} <ArrowUpRight size={14}/></button></div></div><div className="aside-foot"><ShieldCheck size={15}/> Your history, always saved.</div></aside>
 <div className="training-main"><section className="logger-card"><div className="exercise-heading"><div><div className="eyebrow">EXERCISE {String(session.plan.indexOf(variant.id)+1).padStart(2,'0')} <span>/ {String(session.plan.length).padStart(2,'0')}</span></div><button className="exercise-title" onClick={()=>setPanel('picker')}>{variant.name}<ChevronDown size={21}/></button><p className="equipment">{variant.equipment}</p></div><span className="equipment-icon"><Dumbbell size={23}/></span></div>
 <div className="previous-line"><History size={15}/><span>Last time</span><strong>{previousSets.length?previousSets.slice(0,3).map(s=>`${s.weight} lb × ${s.reps}`).join(' · '):'First time here'}</strong>{previous[0]?.createdAt===0&&<span className="seed-tag">Seeded</span>}</div>
 <div className={`recommendation ${rec.status==='pause'?'caution':''}`} aria-live="polite"><div className="recommendation-top"><span className="coach-badge"><Activity size={15}/> {rec.label}</span><span className="target-pill">{rec.min}–{rec.max} reps · {rec.targetRir}{rec.targetRir===3?'+':''} RIR</span></div><div className="recommendation-value">{rec.status==='pause'||rec.status==='complete'?rec.label:rec.weight===null?'Choose a starting load':<>{rec.weight}<span> lb</span><span className="times">×</span>{rec.reps}<span> reps</span></>}</div><details className="recommendation-details"><summary>Why this set?</summary><p>{rec.reason}</p></details></div>
 <div className="set-config"><Choice label="Set type" value={kind} onChange={s=>{setKind(s as SetType);if(recommend(variant,session,data.sets,activeSide,s as SetType).weight!==null)setDraft(null);}} items={Object.entries(typeLabels) as [string,string][]}/>{variant.unilateral?<Segments label="Leg or arm" value={side} onChange={s=>{setSide(s as Side);setDraft(null);}} items={[{id:'left',label:'Left'},{id:'right',label:'Right'}]}/>:<span className="set-count">{count>=goal?"Target complete":`Set ${count+1} of ${goal}`}</span>}</div>
 <fieldset disabled={busy} className="entry-fields"><div className="counter-grid"><Counter label="Weight" value={weight} unit={`lb · ${variant.loadMode}`} step={variant.increment} onChange={v=>setDraft({weight:v,reps})}/><Counter label="Reps" value={reps} unit="completed" max={100} onChange={v=>setDraft({weight,reps:Math.max(1,v)})}/></div><div className="rir-heading"><label>Reps in reserve <span>(RIR)</span></label><span>How many more?</span></div><Segments label="Reps in reserve" value={rir} onChange={setRir} items={[{id:'0',label:'0',hint:'Failure'},{id:'1',label:'1',hint:'Hard'},{id:'2',label:'2',hint:'Solid'},{id:'3',label:'3+',hint:'Easy'}]}/>
 <button className="log-button" onClick={log} disabled={weight===null||busy||rec.status==='pause'||rec.status==='complete'}>{busy?<LoaderCircle className="spin" size={22}/>:<Plus size={23}/>}<span>{busy?'Saving set…':'Log Set'}</span><span className="log-side">{variant.unilateral?`${side==='left'?'L':'R'} · ${count+1}/${goal}`:`${count+1}/${goal}`}</span></button></fieldset>
 <div className="log-footer"><button onClick={()=>setPanel('pain')}><NotebookPen size={15}/>{painSeverity||setNote?'Note added':'Pain or set note'}</button><span><CheckCheck size={15}/>{error?'Save not confirmed':lastSaved?'Saved to your history':'Saves after every set'}</span></div>
 {(rec.status==='complete'||rec.status==='pause')&&<button className="wide-button" onClick={nextExercise}>Continue workout <ArrowRight size={18}/></button>}
 </section>
 <button className="coach-strip" onClick={()=>setPanel('coach')}><span className="coach-strip-icon"><MessageCircle size={21}/></span><span><strong>Tell coach</strong><small>Feeling tired? Need to change the plan?</small></span><ArrowUpRight size={20}/></button>{ruleChips(session)}
 <section className="today-sets"><div className="section-heading"><h2>Sets this workout</h2><span>{currentSets.length} logged</span></div>{currentSets.length?setRows(currentSets,true):<div className="empty-sets"><span className="empty-dash">—</span><p>Your first set goes here.<br/><span>One set at a time.</span></p></div>}</section><button className="mobile-plan" onClick={()=>setPanel('picker')}>View workout · {session.plan.length} exercises <ChevronRight size={18}/></button>
 </div></div></>:<div className="welcome-card"><span className="large-icon"><CheckCheck size={32}/></span><p className="eyebrow">READY WHEN YOU ARE</p><h1>{data.sets.length>1?'Workout complete.':'Let’s get a session in.'}</h1><p>Your sets and recommendations are saved. Start a fresh session with your last exercise lineup.</p><label className="form-field">Workout name<input value={sessionName} onChange={e=>setSessionName(e.target.value)}/></label><button className="log-button" onClick={start} disabled={busy||!data.variants.length}><Plus/> Start workout</button></div>}
 </TabsContent>
 <TabsContent value="history"><div className="page-heading"><div><p className="eyebrow">THE WORK ADDS UP</p><h1>Training history</h1><p className="heading-meta">Every session. Every set.</p></div></div><div className="history-layout"><section className="panel-card"><div className="section-heading"><h2>Sessions</h2><span>{data.sessions.filter(s=>s.status!=='seed').length} workouts</span></div>{data.sessions.slice().sort((a,b)=>b.startedAt-a.startedAt).map(s=><button className={`history-session ${historyId===s.id?'active':''}`} key={s.id} onClick={()=>setHistoryId(s.id)}><span className="calendar-icon"><History size={22}/></span><span><strong>{s.name}</strong><small>{date(s.startedAt)} · {data.sets.filter(x=>x.sessionId===s.id).length} sets</small></span><span className="status-tag">{s.status==='seed'?'Imported':s.status==='active'?'In progress':'Complete'}</span><ChevronRight size={17}/></button>)}</section><section className="panel-card"><div className="section-heading"><h2>{historySession?.name??'Progression'}</h2>{historySession&&<button className="text-button" onClick={()=>setHistoryId('')}>View progression</button>}</div>{historySession?<><p className="muted">{historySession.notes||'No workout notes.'}</p>{ruleChips(historySession)}{historySession.plan.map(id=>{const v=data.variants.find(v=>v.id===id),sets=data.sets.filter(s=>s.sessionId===historySession.id&&s.variantId===id).sort((a,b)=>a.createdAt-b.createdAt);return sets.length?<div key={id} className="history-exercise"><h3>{v?.name}</h3>{setRows(sets)}</div>:null;})}{!data.sets.some(s=>s.sessionId===historySession.id)&&<p className="muted">No sets logged yet.</p>}</>:<><Choice label="Progression exercise" value={historyVariant} onChange={setHistoryVariant} items={[["all","All exercises"],...data.variants.map(v=>[v.id,v.name] as [string,string])]}/><p className="muted small-copy">Recommendations are kept alongside the set that produced them.</p>{data.progressions.filter(p=>historyVariant==='all'||p.variantId===historyVariant).sort((a,b)=>b.createdAt-a.createdAt).map(p=>{const s=data.sets.find(s=>s.id===p.setId),v=data.variants.find(v=>v.id===p.variantId);return <div key={p.id} className="progression-row"><span className="progression-dot"/><div><small>{date(p.createdAt)} · {s?sideLabel(s.side):''}</small><h3>{v?.name}</h3><p>{s?.weight} lb × {s?.reps} <ArrowRight size={13}/> <strong>{p.recommendation.status==='ready'?`${p.recommendation.weight} lb × ${p.recommendation.reps}`:p.recommendation.label}</strong></p><small>{p.recommendation.reason}</small></div></div>;})}{!data.progressions.length&&<div className="empty-message"><Activity size={28}/><h3>Your next set starts the story.</h3><p>Log a set to see how your recommendations evolve.</p></div>}</>}</section></div></TabsContent>
 <TabsContent value="exercises"><div className="page-heading"><div><p className="eyebrow">YOUR EQUIPMENT, YOUR WAY</p><h1>Exercises</h1><p className="heading-meta">Variants keep their own targets and history.</p></div><button className="primary-small" onClick={()=>setPanel('new')}><Plus size={18}/> Add</button></div><div className="variant-grid">{data.variants.map(v=><article className="variant-card" key={v.id}><div className="variant-card-top"><span className="equipment-icon"><Dumbbell size={22}/></span><span className="tag">{v.unilateral?'Unilateral':'Bilateral'}</span></div><h2>{v.name}</h2><p>{v.equipment}</p><div className="variant-stats"><span>{v.minReps}–{v.maxReps} reps</span><span>{v.defaultSets} sets</span><span>{v.increment} lb steps</span></div><small>Load: {v.loadMode}</small><div className="variant-actions"><button className="text-button" onClick={()=>{setTargetVariant(v);setPanel('targets');}}>Edit targets <SlidersHorizontal size={15}/></button><button className="icon-button" aria-label={`Add variant of ${v.name}`} onClick={()=>{setForm({...form,exerciseId:v.exerciseId,baseName:'',name:'',equipment:v.equipment,unilateral:!!v.unilateral,loadMode:v.loadMode,increment:v.increment,minReps:v.minReps,maxReps:v.maxReps,defaultSets:v.defaultSets});setPanel('new');}}><Plus size={19}/></button></div></article>)}</div></TabsContent>
 <TabsContent value="coach"><div className="page-heading"><div><p className="eyebrow">ADAPT AS YOU GO</p><h1>Your coach</h1><p className="heading-meta">Small adjustments. Better next sets.</p></div></div><div className="coach-page panel-card">{session?<><div className="section-heading"><h2>{session.name}</h2><span>Current workout</span></div>{ruleChips(session)}<p className="muted">Tell me what needs to change. Adjustments apply to the rest of this workout.</p><div className="quick-prompts">{['Go lighter','Only 2 sets per exercise','No failure','I have 20 minutes'].map(t=><button disabled={busy} onClick={()=>void tell(t)} key={t}>{t}</button>)}</div><div className="messages">{data.messages.filter(m=>m.sessionId===session.id).sort((a,b)=>a.createdAt-b.createdAt).map(m=><div key={m.id}><div className="user-message">{m.message}</div><div className="coach-message"><Activity size={20}/><p>{m.response}</p></div></div>)}</div><form className="coach-form" onSubmit={e=>{e.preventDefault();void tell();}}><textarea value={coachText} onChange={e=>setCoachText(e.target.value)} aria-label="Tell coach" placeholder="e.g. I’m tired. Go lighter and skip leg press." rows={3}/><button className="primary-small" disabled={busy||!coachText.trim()}>Update workout <ArrowUpRight size={18}/></button></form><p className="small-copy muted">Adaptive coaching uses your logged performance and supported instructions. Unrecognized requests are saved as notes.</p></>:<p>Start a workout to adjust your plan with coach.</p>}</div></TabsContent>
 </>}
 </Tabs>
 <Sheet open={!!panel} onOpenChange={open=>{if(!open)setPanel('');}}><SheetContent side="bottom" className="bottom-sheet"><SheetHeader><SheetTitle>{({picker:'Your workout',pain:'How did that feel?',coach:'Tell coach',session:'Workout notes',finish:'Finish your workout?',new:'Add an exercise variant',targets:'Exercise targets'} as Record<string,string>)[panel]}</SheetTitle><SheetDescription>{({picker:'Choose an exercise, or add one to today’s lineup.',pain:'Optional. This note will be saved with your next set.',coach:'Adjust the remaining workout. Your changes are saved.',session:'Keep your focus and context with this session.',finish:'Your sets and coaching history will stay saved.',new:'Use a new variant for a different machine, stance, or setup.',targets:'These defaults apply to future recommendations.'} as Record<string,string>)[panel]}</SheetDescription></SheetHeader><div className="sheet-body">
 {panel==='picker'&&exerciseList(true)}
 {panel==='pain'&&<><label className="form-field">Pain location<input value={painLocation} onChange={e=>setPainLocation(e.target.value)} placeholder="e.g. left knee" maxLength={100}/></label><div className="quick-prompts">{['Knee','Ankle','Achilles','Lower back','Hip'].map(t=><button key={t} onClick={()=>setPainLocation(`${activeSide==='both'?'':activeSide+' '}${t.toLowerCase()}`)}>{t}</button>)}</div><Counter label="Pain severity" unit="0–10" value={painSeverity} max={10} onChange={setPainSeverity}/><label className="form-field">Set note<textarea rows={2} value={setNote} onChange={e=>setSetNote(e.target.value)} placeholder="Technique, range of motion, anything useful…" maxLength={1000}/></label><button className="log-button" disabled={painSeverity>0&&!painLocation.trim()} onClick={()=>setPanel('')}><Check/> Keep with next set</button>{painSeverity>0&&<p className="muted small-copy">After saving this set, recommendations for this side will pause.</p>}</>}
 {panel==='coach'&&<><div className="quick-prompts">{['Go lighter','2 sets per exercise','Skip this exercise','No failure'].map(t=><button key={t} disabled={busy} onClick={()=>void tell(t)}>{t}</button>)}</div><form className="coach-form" onSubmit={e=>{e.preventDefault();void tell();}}><textarea aria-label="Tell coach" rows={3} value={coachText} onChange={e=>setCoachText(e.target.value)} placeholder="What should change?"/><button className="log-button" disabled={busy||!coachText.trim()}>Update workout <ArrowUpRight size={20}/></button></form>{data.messages.filter(m=>m.sessionId===session?.id).sort((a,b)=>b.createdAt-a.createdAt).slice(0,1).map(m=><div className="coach-message" key={m.id}><Activity size={20}/><p>{m.response}</p></div>)}</>}
 {panel==='session'&&session&&<><label className="form-field">Workout name<input value={sessionName} onChange={e=>setSessionName(e.target.value)} maxLength={80}/></label><label className="form-field">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} placeholder="Focus, equipment changes, or context for today…" maxLength={4000}/></label>{ruleChips(session)}<button className="text-button" onClick={()=>setPanel('coach')}>Change workout constraints <ArrowUpRight size={16}/></button><button className="log-button" disabled={busy||!sessionName.trim()} onClick={async()=>{if(await mutate({action:'session',sessionId:session.id,name:sessionName,notes,plan:session.plan}))setPanel('');}}>Save notes <Check size={20}/></button></>}
 {panel==='finish'&&session&&<><div className="finish-stats"><div><strong>{workoutSets.length}</strong><span>sets logged</span></div><div><strong>{new Set(workoutSets.map(s=>s.variantId)).size}</strong><span>exercises trained</span></div></div><button className="log-button" disabled={busy} onClick={async()=>{const d=await mutate({action:'finish',sessionId:session.id});if(d){setPanel('');setHistoryId(session.id);toast.success('Workout saved. Nice work.');}}}><CheckCheck/> Finish & save</button><button className="wide-button" onClick={()=>setPanel('')}>Keep training</button></>}
 {panel==='new'&&<form className="exercise-form" onSubmit={async e=>{e.preventDefault();const d=await mutate({action:'variant',id:newId(),...form,exerciseId:form.exerciseId==='new'?'':form.exerciseId});if(d){setPanel('');setTab('exercises');toast.success('Exercise variant saved');}}}><label className="form-field">Base exercise<Choice label="Base exercise" value={form.exerciseId} onChange={v=>setForm({...form,exerciseId:v})} items={[["new","New exercise"],...data.exercises.map(e=>[e.id,e.name] as [string,string])]}/></label>{form.exerciseId==='new'&&<label className="form-field">Base name<input required value={form.baseName} onChange={e=>setForm({...form,baseName:e.target.value})} placeholder="e.g. Split squat"/></label>}<label className="form-field">Variant name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Rear-foot elevated dumbbell split squat"/></label><label className="form-field">Equipment<input required value={form.equipment} onChange={e=>setForm({...form,equipment:e.target.value})}/></label><label className="switch-field">Track left and right separately<Switch checked={form.unilateral} onCheckedChange={v=>setForm({...form,unilateral:v})}/></label><label className="form-field">Weight represents<Choice label="Weight representation" value={form.loadMode} onChange={v=>setForm({...form,loadMode:v})} items={['per dumbbell','total load','per leg','machine load'].map(v=>[v,v])}/></label><div className="form-grid">{(['minReps','maxReps','increment','defaultSets'] as const).map((key,i)=><label className="form-field" key={key}>{['Min reps','Max reps','lb increment','Working sets'][i]}<input required type="number" min={key==='increment'?.5:1} max={key==='defaultSets'?10:key==='increment'?100:50} step={key==='increment'?.5:1} value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/></label>)}</div><button className="log-button" disabled={busy}>Save exercise <Check size={20}/></button></form>}
 {panel==='targets'&&targetVariant&&<form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'targets',variantId:targetVariant.id,increment:targetVariant.increment,minReps:targetVariant.minReps,maxReps:targetVariant.maxReps,defaultSets:targetVariant.defaultSets})){setDraft(null);setPanel('');toast.success('Targets updated');}}}><h3>{targetVariant.name}</h3><div className="form-grid">{(['minReps','maxReps','increment','defaultSets'] as const).map((key,i)=><label className="form-field" key={key}>{['Min reps','Max reps','lb increment','Working sets'][i]}<input required type="number" min={key==='increment'?.5:1} max={key==='defaultSets'?10:key==='increment'?100:50} step={key==='increment'?.5:1} value={targetVariant[key]} onChange={e=>setTargetVariant({...targetVariant,[key]:Number(e.target.value)})}/></label>)}</div><p className="small-copy muted">An active coach constraint takes priority over these defaults.</p><button className="log-button" disabled={busy}>Save targets <Check size={20}/></button></form>}
 {error&&<p role="alert" className="sheet-error">{error}</p>}
 </div></SheetContent></Sheet>
 </div>;
}
