'use client';
import {useEffect,useState} from 'react';
export function AccountPanel(){
 const [info,setInfo]=useState<{account:{name:string;canInvite:boolean};partner:{name:string;version:number}|null}|null>(null),[name,setName]=useState('Partner'),[key,setKey]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reset,setReset]=useState(false);
 async function load(){const r=await fetch('/api/account',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setInfo(d);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function create(){setBusy(true);setError('');setKey('');try{const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(info?.partner?{action:'reset_partner_key',expectedVersion:info.partner.version}:{action:'create_partner',name})}),d=await r.json();if(!r.ok)throw new Error(d.error);setKey(d.key);setReset(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="account-panel"><p>Signed in as <strong>{info?.account.name??'…'}</strong>. Plans, sets and progression belong to this account.</p>{error&&<p role="alert">{error}</p>}{info?.account.canInvite&&<section><h3>Partner access</h3><p>Your partner uses this same site with a separate private key. Their plan and history start fresh.</p>{info.partner?<><p>Account: {info.partner.name}</p>{!reset?<button className="quiet-button" onClick={()=>setReset(true)}>Replace partner’s sign-in key</button>:<><p>This signs your partner out on all devices. Their saved workouts stay intact.</p><button className="quiet-button" disabled={busy} onClick={create}>Replace key and sign out their devices</button><button className="text-button" onClick={()=>setReset(false)}>Cancel</button></>}</>:<><label className="form-field">Partner’s name<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><button className="log-button" disabled={busy||!name.trim()} onClick={create}>Create partner access</button></>}{key&&<div role="status"><p>Save this key and share it privately with your partner. It is only shown now.</p><label className="form-field">Partner sign-in key<textarea readOnly value={key} style={{overflowWrap:'anywhere',minHeight:100}} onFocus={e=>e.target.select()}/></label><button className="quiet-button" onClick={()=>navigator.clipboard.writeText(`Setwise: ${location.origin}/login\nSign-in key: ${key}`).catch(()=>setError('Select and copy the key above.'))}>Copy sign-in details</button></div>}</section>}<hr/><a className="text-button" href="/api/export">Download my workout backup</a><form action="/logout" method="post"><button className="quiet-button" style={{marginTop:20}}>Sign out</button></form></div>;
}
