import { sqliteTable, text, integer, real, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const profiles = sqliteTable('profiles', { owner: text('owner').primaryKey(), createdAt: integer('created_at').notNull() });
export const routineRevisions=sqliteTable('routine_revisions',{
  owner:text('owner').notNull(),revision:integer('revision').notNull(),requestId:text('request_id').notNull(),createdAt:integer('created_at').notNull(),reason:text('reason').notNull(),routine:text('routine').notNull(),
},t=>[uniqueIndex('idx_routine_owner_revision').on(t.owner,t.revision),uniqueIndex('idx_routine_owner_request').on(t.owner,t.requestId)]);
export const exercises = sqliteTable('exercises', { id: text('id').primaryKey(), owner: text('owner').notNull(), name: text('name').notNull() }, t => [index('idx_exercises_owner').on(t.owner)]);
export const variants = sqliteTable('variants', {
  id: text('id').primaryKey(), owner: text('owner').notNull(), exerciseId: text('exercise_id').notNull().references(()=>exercises.id), name: text('name').notNull(), equipment: text('equipment').notNull(), unilateral: integer('unilateral').notNull(), loadMode: text('load_mode').notNull(), increment: real('increment').notNull(), minReps: integer('min_reps').notNull(), maxReps: integer('max_reps').notNull(), defaultSets: integer('default_sets').notNull(),
},t=>[index('idx_variants_owner').on(t.owner)]);
export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey(), owner: text('owner').notNull(), name: text('name').notNull(), startedAt: integer('started_at').notNull(), endedAt: integer('ended_at'), status: text('status').notNull(), notes: text('notes').notNull(), plan: text('plan').notNull(), rules: text('rules').notNull(), prescriptions:text('prescriptions').notNull().default('[]'),routineRevision:integer('routine_revision'),
},t=>[index('idx_sessions_owner_started').on(t.owner,t.startedAt),uniqueIndex('idx_sessions_one_active').on(t.owner).where(sql`${t.status} = 'active'`)]);
export const sets = sqliteTable('sets', {
  id: text('id').primaryKey(), owner: text('owner').notNull(), sessionId: text('session_id').notNull().references(()=>sessions.id), variantId: text('variant_id').notNull().references(()=>variants.id), createdAt: integer('created_at').notNull(), weight: real('weight').notNull(), reps: integer('reps').notNull(), rir: integer('rir'), side: text('side').notNull(), type: text('type').notNull(), painLocation: text('pain_location').notNull(), painSeverity: integer('pain_severity').notNull(), note: text('note').notNull(), suggestedWeight: real('suggested_weight'), suggestedReps: integer('suggested_reps'),
},t=>[index('idx_sets_owner_variant_time').on(t.owner,t.variantId,t.createdAt),index('idx_sets_owner_session').on(t.owner,t.sessionId)]);
export const coachMessages = sqliteTable('coach_messages', { id:text('id').primaryKey(), owner:text('owner').notNull(), sessionId:text('session_id').notNull().references(()=>sessions.id), createdAt:integer('created_at').notNull(), message:text('message').notNull(), response:text('response').notNull(),requestPayload:text('request_payload') },t=>[index('idx_coach_owner_session').on(t.owner,t.sessionId)]);
export const progressions = sqliteTable('progressions', {id:text('id').primaryKey(), owner:text('owner').notNull(), sessionId:text('session_id').notNull().references(()=>sessions.id), setId:text('set_id').notNull().references(()=>sets.id), variantId:text('variant_id').notNull().references(()=>variants.id), createdAt:integer('created_at').notNull(), recommendation:text('recommendation').notNull()},t=>[index('idx_progressions_owner_variant').on(t.owner,t.variantId,t.createdAt)]);

export const privateAccounts=sqliteTable('private_accounts',{owner:text('owner').primaryKey(),slot:text('slot').notNull().unique(),name:text('name').notNull(),keyHash:text('key_hash').notNull().unique(),sessionVersion:integer('session_version').notNull().default(1),createdAt:integer('created_at').notNull()});
