import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {readFile,readdir,writeFile,mkdir} from 'node:fs/promises';
await build({entryPoints:['preview/render.tsx'],bundle:true,platform:'node',format:'esm',outfile:'/workspace/sites/setwise/.sites-runtime/review-render.mjs',packages:'external',jsx:'automatic'});
const {renderReview}=await import(pathToFileURL('/workspace/sites/setwise/.sites-runtime/review-render.mjs'));
const markup=renderReview();
const bundle=await build({entryPoints:['preview/entry.tsx'],bundle:true,platform:'browser',format:'iife',write:false,minify:true,define:{'process.env.NODE_ENV':'"production"'},jsx:'automatic'});
const names=await readdir('dist/client/assets');
const css=(await Promise.all(names.filter(n=>n.endsWith('.css')).map(n=>readFile('dist/client/assets/'+n,'utf8')))).join('\n');
const js=bundle.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Setwise — Interactive preview</title><style>'+css+'\n.review-banner{font-family:Arial,sans-serif;background:#dfedc9;color:#2f5127;font-size:12px;padding:6px 12px;text-align:center;font-weight:700;letter-spacing:.6px}.review-banner span{display:inline;margin-left:8px;font-weight:400;letter-spacing:0;margin-top:4px;font-size:12px}</style></head><body><div id="root">'+markup+'</div><noscript><p style="padding:16px;font-family:Arial">This file viewer cannot run the app. Use the owner-only Site once activated for real workout logging.</p></noscript><script>'+js+'</script></body></html>';
await mkdir('/workspace/scratch/dbccf67e112f/deliverables',{recursive:true});
await writeFile('/workspace/scratch/dbccf67e112f/deliverables/setwise-preview.html',html);
console.log('Interactive preview written:',Buffer.byteLength(html),'bytes.');
